TrajectoryPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 4 # X 方向最大速度
  min_vel_x: -4 # X 方向最小速速

  max_vel_theta: 10.
  min_vel_theta: -10.

  min_in_place_vel_theta: 0.4

  acc_lim_x: 3 # X 加速限制
  acc_lim_y: 3 # Y 加速限制
  acc_lim_theta: 3.2 # 角速度加速限制（弧度/秒）

# Goal Tolerance Parameters，目标公差
  xy_goal_tolerance: 0.10
  yaw_goal_tolerance: 0.1

# Differential-drive robot configuration
# 是否是全向移动机器人
  holonomic_robot: true
  dwa: false
# Forward Simulation Parameters，前进模拟参数，可通过调试如下参数，使局部路径规划更贴合全局路径规划
  sim_time: 1.7  # 提高sim_time值可使局部路径规划更符合全局路径规划
  vx_samples: 20
  vtheta_samples: 20
  angular_sim_granularity: 0.025
  sim_granularity: 0.05

  heading_scoring: false
  heading_lookahead: 0.0325
  occdist_scale: 0.1
  path_distance_bias: 0.6
  goal_distance_bias: 0.8
